### PR TITLE
Prevent macro wrong place in hierarchy (only at the bottom)

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
cc @gkoz

### CODE REVIEW

**Comment by gkoz** [comment]
We don't really need the interface now do we? gir could work with the library directly.

**Comment by GuillaumeGomez** [comment]
Yes, that's what I said before you wanted to be splitted out. :)

**Comment by gkoz** [comment]
You keep implying that I wanted the `stripper_interface` to exist but I don't have a recollection of that.

**Comment by GuillaumeGomez** [comment]
Then it's certainly a misunderstanding. You wanted a standalone interface for `rustdoc-stripper` types for `gir` and I understood you wanted a crate. Like I said, it doesn't matter, we can just put the code back.

**Pull request merged**
